apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: project-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: N8N_WEBHOOK_URL
          value: "http://n8n-service:5678/webhook/send_notification"
        - name: OAUTH_REDIRECT_URI
          value: "http://localhost:30080/auth/callback"
        volumeMounts:
        - name: google-secret
          mountPath: /app/backend/client_secrets.json
          subPath: client_secrets.json
          readOnly: true
        - name: google-token
          mountPath: /app/backend/token.pickle
          subPath: token.pickle
          readOnly: true
      volumes:
      - name: google-secret
        secret:
          secretName: google-oauth-secret
      - name: google-token
        secret:
          secretName: google-token-secret
